### ISSUE TITLE
Submitting anything in the app leads to HTTP 502

### ISSUE THREAD

**Issue by hongshaoyang** [Aishwarya26l/vueTestingSuite#2]
After submitting my editable code, the POST always responds with HTTP 502 Bad Gateway with a "Internal Server Error" message.

Testing the API on the AWS API Gateway console with a POST request body like this:

```json
{
    "userToken": "ABCDE",
    "shown": {
        "0": "//main.spec.js \nconst app = require(\"./main\");\ndescribe(\"Load app from main.js\", () => {\n    it(\"has a created hook\", () => {\n        expect(typeof app).toBe(\"object\");\n    });\n    it(\"sets the correct default data\", () => {\n        expect(typeof app).toBe(\"object\");\n        expect(2).toEqual(2);\n        expect(app.user).toEqual(\"Chris\");\n    });\n});"
    },
    "editable": {
        "0": "//main.js \nvar app = new Vue({\n    el: \"#app\",\n    data: {\n        user: \"Chris\",\n        temp: 95\n    }\n});\nmodule.exports = app;"
    },
    "hidden": {
        "0": "{\n    \"scripts\": {\n        \"test\": \"jest\"\n    }\n}"
    }
}
```

leads to this error message:
```
Sat Oct 05 15:13:25 UTC 2019 : Endpoint response body before transformations: {"errorType":"SyntaxError","errorMessage":"Unexpected end of JSON input","trace":["SyntaxError: Unexpected end of JSON input","    at JSON.parse (<anonymous>)","    at testRunner (/var/task/testRunner.js:87:40)","    at Runtime.exports.handler (/var/task/index.js:25:23)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}
Sat Oct 05 15:13:25 UTC 2019 : Lambda execution failed with status 200 due to customer function error: Unexpected end of JSON input. Lambda request id: 7d2d7f6c-c134-4ba2-96ec-90ef55b97146
```

The offending code in `testRunner.js` is this part:

```javascript
      let npmTest = "cd /tmp/example; CI=true npm test";
      let npmTestResults = systemSync(npmTest);

      let npmTestJSON = "cd /tmp/example; CI=true npm run test-json";
      let npmTestJSONResults = systemSync(npmTestJSON);
      let finalnpmTestJSONResults = {};

      if (typeof npmTestJSONResults === "string") {
        let lines = npmTestJSONResults.split("\n");
        // remove three lines, starting at the first position
        lines.splice(0, 3);
        // join the array back into a single string
        let newtext = lines.join("\n");
        finalnpmTestJSONResults = JSON.parse(newtext);
      } else {
        finalnpmTestJSONResults = npmTestJSONResults;
      }
```

where the `JSON.parse` is not parsing correctly.

**Comment by Aishwarya26l** [comment]
POST calls to the API - 

POST request - 
```javascript 
{
"userToken":"ABCDE",
"shown":{"0":"//main.spec.js \nconst app = require(\"./main\");\ndescribe(\"Load app from main.js\", () => {\n    it(\"has a created hook\", () => {\n        expect(typeof app).toBe(\"object\");\n    });\n    it(\"sets the correct default data\", () => {\n        expect(typeof app).toBe(\"object\");\n        expect(2).toEqual(2);\n        expect(app.user).toEqual(\"Chris\");\n    });\n});"},
"editable":{"0":"//main.js \nvar app = new Vue({\n    el: \"#app\",\n    data: {\n        user: \"Chris\",\n        temp: 95\n    }\n});\nmodule.exports = app;"},
"hidden":{"0":"{\n    \"scripts\": {\n        \"test\": \"jest\"\n    }\n}"}
}
```
POST response - 
```Javascript
{
"isComplete":true,
"jsonFeedback":{"numFailedTestSuites":0,"numFailedTests":0,"numPassedTestSuites":1,"numPassedTests":2,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":1,"numTotalTests":2,"openHandles":[],"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesRemovedList":[],"filesUnmatched":0,"filesUpdated":0,"matched":0,"total":0,"unchecked":0,"uncheckedKeysByFile":[],"unmatched":0,"updated":0},"startTime":1571022833409,"success":true,"testResults":[{"assertionResults":[{"ancestorTitles":["Load app from main.js"],"failureMessages":[],"fullName":"Load app from main.js has a created hook","location":null,"status":"passed","title":"has a created hook"},{"ancestorTitles":["Load app from main.js"],"failureMessages":[],"fullName":"Load app from main.js sets the correct default data","location":null,"status":"passed","title":"sets the correct default data"}],"endTime":1571022835324,"message":"","name":"/tmp/example/main.spec.js","startTime":1571022834465,"status":"passed","summary":""}],"wasInterrupted":false},
"htmlFeedback":"<h4>npm test results :- </h4>\n> jestrunner@1.0.0 test /tmp/example\n> jest --colors 2>&1 | aha\n\n<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<!-- This file was created with the aha Ansi HTML Adapter. https://github.com/theZiz/aha -->\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"application/xml+xhtml; charset=UTF-8\"/>\n<title>stdin</title>\n</head>\n<body>\n<pre>\n<span style=\"color:white;background-color:black;\"></span><span style=\"font-weight:bold;color:white;background-color:black;\"></span><span style=\"font-weight:bold;color:white;background-color:green;\"> PASS </span><span style=\"font-weight:bold;color:white;background-color:black;\"></span><span style=\"color:white;background-color:black;\"></span><span style=\"color:black;background-color:white;\"></span> ./<span style=\"font-weight:bold;\">main.spec.js</span>\n  Load app from main.js\n    <span style=\"color:green;\">✓</span><span style=\"color:black;\"> has a created hook (2ms)\n    </span><span style=\"color:green;\">✓</span><span style=\"color:black;\"> sets the correct default data (2ms)\n\n</span><span style=\"font-weight:bold;color:black;\">Test Suites: </span><span style=\"color:black;\"></span><span style=\"font-weight:bold;color:black;\"></span><span style=\"font-weight:bold;color:green;\">1 passed</span><span style=\"font-weight:bold;color:black;\"></span><span style=\"color:black;\">, 1 total\n</span><span style=\"font-weight:bold;color:black;\">Tests:       </span><span style=\"color:black;\"></span><span style=\"font-weight:bold;color:black;\"></span><span style=\"font-weight:bold;color:green;\">2 passed</span><span style=\"font-weight:bold;color:black;\"></span><span style=\"color:black;\">, 2 total\n</span><span style=\"font-weight:bold;color:black;\">Snapshots:   </span><span style=\"color:black;\">0 total\n</span><span style=\"font-weight:bold;color:black;\">Time:</span><span style=\"color:black;\">        1.94s\n</span></pre>\n</body>\n</html>\n",
"textFeedback":"Total test suites = 1\nTest suits Passed = 1"
}
```

Please refer to the latest code changes which runs "npm install" in the environment to enable the use of jest. 

Please pull the latest changes and try again. 

If the issue still persists, re-open the issue with additional cloudwatch logs.
